# yaml-language-server: $schema=../../../schemas/config.schema.json
# yaml-language-server: $schema=https://raw.githubusercontent.com/Team-Sneakymouse/DippGen/main/schemas/config.schema.json
replacements:
  ore:
    blocks:
      - material: RAW_IRON_BLOCK
        weight: 1
    minDelay: 5
    maxDelay: 10
    coordinates:
      - -414 68 -317
      - -412 68 -317
  flowers:
    blocks:
      - material: GRASS
        weight: 2
      - material: DANDELION
        weight: 3
      - material: POPPY
        weight: 3
      - material: ALLIUM
        weight: 1
      - material: BLUE_ORCHID
        weight: 1
    minDelay: 30
    maxDelay: 60
    coordinates:
      - 4965 61 4997
      - 4931 61 4928
      - 4981 61 4984
      - 4967 61 4969
      - 4927 61 4987
      - 4993 61 4993
