# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin
name: dipp-generate
main: com.danidipp.lom.Plugin
version: 1.0
api-version: 1.20
depend:
    - WorldGuard

commands:
    register:
        description: Registers new location
        # permission: dipp.commands.register
        usage: /<command> <list>
    reload:
        description: Reloads config
        # permission: dipp.commands.reload
        usage: /<command>
    plotbuy:
        description: Make player buy plot
        permission: dipp.commands.plotbuy
        usage: /<command> <player>
    plotsell:
        description: Make player sell plot
        permission: dipp.commands.plotsell
        usage: /<command> <player>
