# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin
name: dippgen
main: com.danidipp.dippgen.Plugin
version: 1.0
api-version: 1.20
depend:
    - WorldGuard

commands:
    reload:
        description: Reloads config
        permission: dipp.commands.reload
        usage: /<command>
    plot:
        description: Open plot management GUI for player
        permission: dipp.commands.plot
        usage: /<command> <player>
    plotbuy:
        description: Make player buy plot
        permission: dipp.commands.plotbuy
        usage: /<command> <player>
    plotsell:
        description: Make player sell plot
        permission: dipp.commands.plotsell
        usage: /<command> <player>
    showbook:
        description: shows book - not to be used manually
        usage: /<command> <hashcode>
    plotshow:
        description: Displays plot info of player
        permission: dipp.commands.plotshow
        usage: /<command> <player>
    deed:
        description: Give deed of current plot to player
        usage: /<command>
