# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin
name: dippgen
main: com.danidipp.dippgen.Plugin
version: 1.0
api-version: 1.20
depend:
    - WorldGuard
softdepend:
    - PlaceholderAPI

commands:
    reload:
        description: Reloads config
        permission: dipp.commands.reload
        usage: /<command>
    plot:
        description: Open plot management GUI for player
        permission: dipp.commands.plot
        usage: /<command> <player>
    showbook:
        description: shows book - not to be used manually
        usage: /<command> <hashcode>
    plotshow:
        description: Displays plot info of player
        permission: dipp.commands.plotshow
        usage: /<command> <player>
    plotchests:
        description: Displays chests and storage within plot
        permission: dipp.commands.plotchests
        usage: /<command> <plot>
    opencontainer:
        description: Opens container at coordinates
        permission: dipp.commands.opencontainer
        usage: /<command> <world> <x> <y> <z>
    deed:
        description: Give deed of current plot to player
        usage: /<command>
    homestone:
        description: Opens homestone management GUI for player
        permission: dipp.commands.homestone
        usage: /<command> <player>
    autopickup:
        description: Toggles autopickup
        permission: dipp.commands.autopickup
        usage: /<command> <player> [duration]
